### ISSUE TITLE
Update to 4.0.0

### ISSUE THREAD

**Issue by DrGuile** [vecnavium-pm-pl/Slapper#10]
Pls update to version 4.0.0 as this is the only plugin which can provide NPC service to my server

**Comment by DretooFuni** [comment]
Please look at both closed and opened issues before creating a new one :)

**Comment by Vecnavium** [comment]
Updates to API4 is soon to come and will come.

**Comment by DrGuile** [comment]
i couldn't find any by name but leave it. Can you tell me the approximate date of when the plugin will support pm4???
(just asking btw)

**Comment by cosmicnebula200** [comment]
> i couldn't find any by name but leave it. Can you tell me the approximate date of when the plugin will support pm4???
> (just asking btw)

Hey @DrGuileDish1 vecna is working on SkyBlockPM and SkyWarsPM currently and he will be getting back to updating the plugin once he is done with thoses. Currently there is no ETA.
