### ISSUE TITLE
Error NameTag

### ISSUE THREAD

**Issue by 0xliam627** [vecnavium-pm-pl/Slapper#17]
Slapper only shows nametag when player put target in Slapper
![notarget](https://user-images.githubusercontent.com/70517151/153606134-b9543a01-a006-4a01-9db0-ef213bb9090f.png)
![target](https://user-images.githubusercontent.com/70517151/153606147-882dec1e-e6c2-4a89-ba93-3fa498bc4b58.png)

**Comment by NhanAZ** [comment]
Same problem

**Comment by BeeAZ-pm-pl** [comment]
Same Problem

**Comment by NoobMCBG** [comment]
Same Problem

**Comment by Mcbeany** [comment]
Same Problem

**Comment by cosmicnebula200** [comment]
Same Problem

**Comment by NhanAZ** [comment]
Can I create a PR for this issue?

**Comment by Vecnavium** [comment]
This has been fixed on the latest release v2.0.2 which can be found [here](https://github.com/vecnavium-pm-pl/Slapper/releases/tag/v2.0.2)
