### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GamerMJay** [vecnavium-pm-pl/Slapper#2]
Hello i have a Question can you SlapperRotaion updaten to Pocketmine api4?

**Comment by Vecnavium** [comment]
Slapper itself isnt fully complete for updates for API 4.0.0, so once Slapper is updated on API 4 then the addons will be updated to API 4.

**Comment by GamerMJay** [comment]
Oh okay thanks

**Comment by Vecnavium** [comment]
No problem
