### ISSUE TITLE
`/slapper` giving no permission message

### ISSUE THREAD

**Issue by ErosionYT** [vecnavium-pm-pl/Slapper#20]
You are still able to create entitiys except when using the `/slapper` it displays `You don't have permission` insted of the message its supposed to display

**Comment by cosmicnebula200** [comment]
> You are still able to create entitiys except when using the `/slapper` it displays `You don't have permission` insted of the message its supposed to display

Hey @ErosionYT ,

Does it happen when you just use `/slapper` without any subcommand?

**Comment by ErosionYT** [comment]
yuh, thats why i said it works
i can show on disc if u need

**Comment by Vecnavium** [comment]
Hi sorry for the late answer, it was fixed a couple of days ago but no release and response was made to the issue.
The issue has been fixed on [this release](https://github.com/vecnavium-pm-pl/Slapper/releases/tag/v2.0.3)
