### ISSUE TITLE
You have no permission to use the command transferserver

### ISSUE THREAD

**Issue by Pinkglitter2216** [vecnavium-pm-pl/Slapper#23]

**Comment by Pinkglitter2216** [comment]
Unfortunately I have a problem with the command transfer server. I gave the command transferserver to the slappers. The command only works once after restarting the server. Then the error message appears: You don't have the permission to use transferserver. The permission is entered correctly for the players: pocketmine.command.transferserver The transfer always works for op players, for normal players only once and then no longer. Can you help me?

**Comment by Ju999** [comment]
I had this problem too. Can players use the Command /transferserver normally? (Is it only appearing if you are trying to execute the command with slappers)

**Comment by Pinkglitter2216** [comment]
Thanks for the tip, I just tested it. The whole command doesn't work, not only for the slappers. What do you think the error could be?

**Comment by Ju999** [comment]
Are you using WaterdogPE?

**Comment by Ju999** [comment]
If you are using Waterdog: https://poggit.pmmp.io/ci/RealBJsingh/Transfer-command-wdpe/Transfer-command-wdpe

If not, try this: https://poggit.pmmp.io/ci/ElectroGamesYT/TransferMe/TransferMe

**Comment by Pinkglitter2216** [comment]
No, we dont work with waterdog.

**Comment by Ju999** [comment]
Did you read the message?

**Comment by Pinkglitter2216** [comment]
Yes, Thanks for the info, I'm testing this right now xD

**Comment by Ju999** [comment]
Ok

**Comment by Pinkglitter2216** [comment]
So i tested it, but it works also only with op...

**Comment by Ju999** [comment]
You need to give the permission `transferme.cmd`

**Comment by Pinkglitter2216** [comment]
Yes of course I did:   - transferme.cmd

**Comment by Ju999** [comment]
Restart server or do /ppreload

**Comment by Pinkglitter2216** [comment]
Yes i know xD

**Comment by Pinkglitter2216** [comment]
But it dont works

**Comment by Ju999** [comment]
It worked for me i removed op from myself and set the group default and it worked..

**Comment by Xd-pro** [comment]
> Thanks for the tip, I just tested it. The whole command doesn't work, not only for the slappers. What do you think the error could be?

That means this isn't a problem with Slapper

**Comment by NhanAZ** [comment]
I think this is not Slapper plugin problem but PurePerms plugin problem.
Try updating your PurePerms to the latest version to get the fix
