### ISSUE TITLE
Slapper Size

### ISSUE THREAD

**Issue by hexer-mc** [vecnavium-pm-pl/Slapper#28]
After a server restart the slapper size is not saved.

**Comment by NhanAZ** [comment]
~~Looks like I have the **same problem** as you~~

**Comment by NhanAZ** [comment]
> ~Looks like I have the **same problem** as you~

This issue has been fixed in version 2.0.4

**Comment by NhanAZ** [comment]
> > ~Looks like I have the **same problem** as you~
> 
> This issue has been fixed in version 2.0.4

Or not =))
