### ISSUE TITLE
Edit bug

### ISSUE THREAD

**Issue by RazzyGP** [vecnavium-pm-pl/Slapper#31]
Slappers do not save edited information once created.

Example: I create a slapper and edit its size to 1.5 in a period of time it will revert to the default size
Other exemple: I create a slapper and try to change its name it will revert to its original name after a while

I observed that this occurs when restarting the server mostly

**Comment by 0xliam627** [comment]
Same problem

**Comment by ghost** [comment]
I have the same problem

**Comment by Atara6431** [comment]
Has this bug been fixed?
