### ISSUE TITLE
Server Crashed On /slapper id 

### ISSUE THREAD

**Issue by dadevguy** [vecnavium-pm-pl/Slapper#35]
* I Tapped Slapper and server Crashed
# Errors
03:10:11.603] [Server thread/CRITICAL]: Error: "Typed static property muqsit\invmenu\InvMenuHandler::$type_registry must not be accessed before initialization" (EXCEPTION) in "/home/container/virions/InvMenu_dev-166.phar/src/muqsit/invmenu/InvMenuHandler" at line 40
--- Stack trace ---
  #0 /home/container/virions/InvMenu_dev-166.phar/src/muqsit/invmenu/InvMenu(31): muqsit\invmenu\InvMenuHandler::getTypeRegistry()
  #1 plugins/Abilities_v1.0.1 (3).phar/src/Main(94): muqsit\invmenu\InvMenu::create(string[13] invmenu:chest)
  #2 plugins/Abilities_v1.0.1 (3).phar/src/Events/SlapperEvents(61): Besher\Abilities\Main->items(object pocketmine\player\Player#34400)
  #3 pmsrc/src/event/RegisteredListener(75): Besher\Abilities\Events\SlapperEvents->onEntityDamage(object pocketmine\event\entity\EntityDamageByEntityEvent#132703)
  #4 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent#132703)
  #5 pmsrc/src/entity/Entity(530): pocketmine\event\Event->call()
  #6 pmsrc/src/entity/Living(517): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#132703)
  #7 pmsrc/src/player/Player(1733): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#132703)
  #8 pmsrc/src/network/mcpe/handler/InGamePacketHandler(516): pocketmine\player\Player->attackEntity(object Besher\Abilities\Npc\SlapperHuman#34447)
  #9 pmsrc/src/network/mcpe/handler/InGamePacketHandler(306): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemOnEntityTransactionData#132599)
  #10 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(105): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#132692)
  #11 pmsrc/src/network/mcpe/NetworkSession(398): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#128811)
  #12 pmsrc/src/network/mcpe/NetworkSession(361): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#132692, string[32] ...........Ar=.BL...............)
  #13 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[104] c.abe.b.j.....g..;.>m?.(.....\..VbU..X.Z... .........|.c..D'.........F.'...w..b_)
  #14 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[113] .c..+yZ=P.........q..!...r..........<......[/ieW..V.A........|e..)...wN.%$#8L...)
  #15 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#33808)
  #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #18 pmsrc/src/Server(1661): pocketmine\snooze\SleeperHandler->sleepUntil(double 1651374611.6104)
  #19 pmsrc/src/Server(1047): pocketmine\Server->tickProcessor()
  #20 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #21 pmsrc/src/PocketMine(327): pocketmine\server()
  #22 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by cosmicnebula200** [comment]
_more like a You issue as i am sure slappers doesnt use invmenu smh_

**Comment by cosmicnebula200** [comment]
#1 plugins/Abilities_v1.0.1 (3).phar/src/Main(94): muqsit\invmenu\InvMenu::create(string[13] invmenu:chest)

**NEXT TIME READ CRASHDUMPS BEFORE ASSUMING ANYTHING**

**Comment by dadevguy** [comment]
BAD PLUGIN: Slapper
 this is in last crash dump

**Comment by cosmicnebula200** [comment]
> BAD PLUGIN: Slapper
>  this is in last crash dump

Its because Slapper->Ability->crash

**Comment by dadevguy** [comment]
how can i fix it

**Comment by cosmicnebula200** [comment]
By opening an issue on the **correct repo smh**

**Comment by dadevguy** [comment]
ok :|
