### ISSUE TITLE
A lot of command can not be used

### ISSUE THREAD

**Issue by Atara6431** [vecnavium-pm-pl/Slapper#39]
/slapper eidt addcommand can't be used,it says that is a unknow command
/slapper help only can see the first page,can't use /slapper help 2

**Comment by PushkarOP** [comment]
Just type this u will get all information how to do

**Comment by PushkarOP** [comment]
Also https://github.com/vecnavium-pm-pl/Slapper#basic-documentation

**Comment by Atara6431** [comment]
it can't work

**Comment by PushkarOP** [comment]
Make sure plugins is enabled successfully

**Comment by PushkarOP** [comment]
Use can check it by using /plugins

**Comment by PushkarOP** [comment]
ok

**Comment by PushkarOP** [comment]
hehe?

**Comment by PushkarOP** [comment]
not hehe
