### ISSUE TITLE
Boot loops

### ISSUE THREAD

**Issue by ErosionYT** [vecnavium-pm-pl/Slapper#40]
After installing slapper on its own with Pocketmine [4.50](https://github.com/pmmp/PocketMine-MP/releases/tag/4.5.0) will cause the server to boot loop

`09:17:48.371] [Server thread/EMERGENCY]: Failed to load some plugins, stopping server to protect server integrity
[09:17:48.371] [Server thread/EMERGENCY]: Forcing server shutdown`

This also does not leave a crash log.

**Comment by xRodzMC** [comment]
Update your slapper plugin.

**Comment by ErosionYT** [comment]
> Update your slapper plugin.

i know.
