### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by EmporiumDevelopment** [vecnavium-pm-pl/Slapper#5]
Left and right click command executors

Example: the slapper is for a shop plugin, Left click sends the player a message for more information about the shop, and right click opens the shop menu

**Comment by PsychoNetworkDev** [comment]
some reason it didnt add the description ill add it here

Left and right click command executors

Example: the slapper is for a shop plugin, Left click sends the player a message for more information about the shop, and right click opens the shop menu

**Comment by Vecnavium** [comment]
You can do that on your own by adding extra commands, Slapper supports more than 1 command and you will need a Shop plugin to have it work. Shop feature will not be added within Slapper.

**Comment by EmporiumDevelopment** [comment]
ye it supports more than one command but it executes them all at the same time
