### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by BoyJPN** [vecnavium-pm-pl/Slapper#52]
[Server thread/CRITICAL]: Could not load plugin 'Slapper': Incompatible network protocol version (plugin requires one of: 544)

**Comment by cosmicnebula200** [comment]
Yes big bug @Vecnavium ples fix. Me use slapper on server mine so ples fix it now. XOXOXOXO

**Comment by dadodasyra** [comment]
"big bug" omegalul

**Comment by cosmicnebula200** [comment]
> "big bug" omegalul

IKR, help me fix thus bug bug and become thiccc

**Comment by xRodzMC** [comment]
Change in `plugin.yml` the following:

```yml
api: 4.0.0
```

Unzip first the plugin using this [website](https://phar.scer.io) and locate `plugin.yml` and edit that line to `4.0.0`. Zip it again, and upload to be `.phar` compiled. Add to your server and enjoy.

> **Warning**
> Not recommended to change, some developers might have protocol version doesn't compatible but anyways it helps.

<p align="right">Follow me for more tutorials: <a href="https://github.com/xqwtxon">@xqwtxon</a> ❤️</p>
