### ISSUE TITLE
PM5 Status ?

### ISSUE THREAD

**Issue by dadodasyra** [vecnavium-pm-pl/Slapper#61]
Is PM5 branch a thing or a forgotten project ?

**Comment by Vecnavium** [comment]
To answer here as well for those who aren't in the PocketMine Community Discord, there is a PM5 branch but yet to be updated. It's a low chance I update Slapper so if anyone wants to update it, simply create a PR and I will review and accept if everything is good.

**Comment by Vecnavium** [comment]
https://github.com/vecnavium-pm-pl/Slapper/tree/pm5 will be moved to main (Master) branch soon
