### ISSUE TITLE
Slapper spawn human Crash

### ISSUE THREAD

**Issue by ghost** [vecnavium-pm-pl/Slapper#7]
[00:31:00.114] [Server thread/CRITICAL]: InvalidArgumentException: "Class slapper\entities\SlapperHuman does not extend slapper\entities\SlapperEntity" (EXCEPTION) in "pmsrc/src/utils/Utils" at line 530

--- Stack trace ---

#0 plugins/Slapper_dev-112 (1).phar/src/slapper/Main(626): pocketmine\utils\Utils::testValidInstance(string[29] slapper\entities\SlapperHuman, string[30] slapper\entities\SlapperEntity)

#1 pmsrc/src/command/PluginCommand(54): slapper\Main->onCommand(object pocketmine\player\Player#99222, object pocketmine\command\PluginCommand#106300, string[7] slapper, array[1])

#2

**Comment by JavierLeon9966** [comment]
Why are you even using the PM4 branch when it hasn't been released yet? Ofc you should expect errors in a non released plugin
