### ISSUE TITLE
Update Protocol version

### ISSUE THREAD

**Issue by MrShrekThird** [vecnavium-pm-pl/Slapper#78]
When I load slapper i get this error message:
[Server thread/CRITICAL]: Could not load plugin 'Slapper': Incompatible network protocol version (plugin requires one of: 589)
 I am on the latest version of PocketMine-MP and the official branch

**Comment by serxhoRTX** [comment]
open the plugin.ym change the versions from 589 to 618 for 1.20.30 or just check https://minecraft.fandom.com/wiki/Bedrock_Edition_1.20.30#:~:text=Protocol%20version&text=1.20.30%20is%20a%20minor,Java%20Edition%2C%20and%20fixes%20bugs. for the latest protocol version

**Comment by kenichi1saito** [comment]
Yes, but where does this plugin.yml appear? It's not showing up on my server
