### ISSUE TITLE
Create a NPC then stop server and run again it does a huge errors

### ISSUE THREAD

**Issue by SattQDV** [vecnavium-pm-pl/Slapper#8]

**Comment by SattQDV** [comment]
PocketMine API 4.0.2

**Comment by SattQDV** [comment]
![Screenshot_2021-12-17-10-54-07-67](https://user-images.githubusercontent.com/96190019/146486443-3afd702e-3b90-41f7-8673-c6cbdaecfaa7.png)
![Screenshot_2021-12-17-10-53-32-08](https://user-images.githubusercontent.com/96190019/146486446-1ff21a3c-6d6b-4f91-b817-e73ebcb5a370.png)
![Screenshot_2021-12-17-10-54-28-79](https://user-images.githubusercontent.com/96190019/146486448-d68a58a5-f4a9-4283-9a13-581742baf2c5.png)
![Screenshot_2021-12-17-10-53-46-77](https://user-images.githubusercontent.com/96190019/146486450-ff0ba1fa-eed3-44f6-9c0a-ac1b3d5ef488.png)
![Screenshot_2021-12-17-10-53-10-67](https://user-images.githubusercontent.com/96190019/146486453-b002ece4-8120-413f-bc43-f9f3f76c7bc8.png)

**Comment by JavierLeon9966** [comment]
Same reason as this comment: https://github.com/vecnavium-pm-pl/Slapper/issues/7#issuecomment-996280324
